import raw from './registry.json'
import { platforms } from './platforms'
import { groups } from './groups'

/** What one platform provides for one component. Generated by `npm run gen`. */
export interface PlatformEntry {
  /** public symbol a developer types, e.g. `UButton` or `up-button` */
  symbol: string
  /** source file, relative to that platform's repo root */
  file?: string
}

export interface ComponentEntry {
  /** url slug, e.g. `button` */
  id: string
  /** group id from data/groups.ts */
  group: string
  name: { zh: string; en: string }
  desc: { zh: string; en: string }
  /** keyed by platform id; a missing key means "not implemented there yet" */
  platforms: Record<string, PlatformEntry>
}

export interface Registry {
  generatedAt: string
  components: ComponentEntry[]
}

export const registry = raw as unknown as Registry

export const components: ComponentEntry[] = registry.components ?? []

export const componentMap: Record<string, ComponentEntry> = Object.fromEntries(
  components.map((c) => [c.id, c])
)

export function getComponent(id: string): ComponentEntry | undefined {
  return componentMap[id]
}

/** Platform ids a component ships on, in canonical platform order. */
export function supportedPlatforms(id: string): string[] {
  const entry = componentMap[id]
  if (!entry) return []
  return platforms.filter((p) => entry.platforms[p.id]).map((p) => p.id)
}

/** Components per group, in canonical group order. Empty groups are dropped. */
export function componentsByGroup(): { group: string; items: ComponentEntry[] }[] {
  return groups
    .map((g) => ({
      group: g.id,
      items: components.filter((c) => c.group === g.id)
    }))
    .filter((g) => g.items.length > 0)
}

/** How many components each platform implements — drives the home page stats. */
export function coverage(): Record<string, number> {
  const out: Record<string, number> = {}
  for (const p of platforms) {
    out[p.id] = components.filter((c) => Boolean(c.platforms[p.id])).length
  }
  return out
}

export const totalComponents = components.length
