/**
 * Curated documentation metadata.
 *
 * `id` is the page slug and the canonical name. `detect` lists the upstream
 * uview-plus component folders that this page covers — sub-components such as
 * `u-cell-group` are folded into their parent page rather than getting one of
 * their own, and the generator treats a page as "supported on a platform" when
 * any of its detect ids resolves there.
 */

const c = (id, group, zh, en, descZh, descEn, detect) => ({
  id,
  group,
  zh,
  en,
  descZh,
  descEn,
  detect: detect ?? [id]
})

export const meta = [
  // ---------------------------------------------------------------- basic
  c('button', 'basic', '按钮', 'Button',
    '最基础的操作单元，内置六种主题、四种尺寸，支持镂空、加载态与渐变色。',
    'The most basic action unit: six themes, four sizes, plus plain, loading and gradient variants.'),
  c('icon', 'basic', '图标', 'Icon',
    '内置字体图标库，同时支持传入图片路径作为图标使用。',
    'A built-in icon font, which also accepts an image path in place of a glyph.'),
  c('image', 'basic', '图片', 'Image',
    '增强版图片组件，提供加载中、加载失败占位与淡入动画。',
    'An enhanced image with loading and error placeholders plus a fade-in transition.'),
  c('text', 'basic', '文本', 'Text',
    '对文本做了主题、省略、脱敏与格式化封装，适合手机号、金额、日期等场景。',
    'Text with theming, truncation, masking and formatting for phone numbers, money and dates.'),
  c('tag', 'basic', '标签', 'Tag',
    '用于标记关键字或分类，支持镂空、圆角与可关闭样式。',
    'Marks keywords or categories; supports plain, rounded and closable styles.'),
  c('badge', 'basic', '徽标数', 'Badge',
    '出现在图标或文字右上角的数字或圆点，用于提示未读数量。',
    'A number or dot pinned to the corner of an icon to signal unread items.'),
  c('avatar', 'basic', '头像', 'Avatar',
    '展示用户头像，支持图片、文字、图标三种内容与头像组堆叠。',
    'Shows a user avatar from an image, text or icon, and can stack into a group.',
    ['avatar', 'avatar-group']),
  c('link', 'basic', '超链接', 'Link',
    '点击后跳转外部链接或复制到剪贴板，自动处理各端差异。',
    'Opens an external URL or copies it to the clipboard, smoothing over platform gaps.'),
  c('title', 'basic', '标题', 'Title',
    '统一的标题排版，提供多级字号与前缀装饰。',
    'Consistent heading typography with several levels and an optional prefix accent.'),
  c('loading-icon', 'basic', '加载动画', 'Loading icon',
    '纯 CSS/原生绘制的加载指示器，提供圆环、花朵、半圆三种形态。',
    'A loading indicator drawn natively, in circle, flower or semicircle form.'),
  c('loading-page', 'basic', '加载页', 'Loading page',
    '覆盖整个页面的加载遮罩，适合首屏或路由切换时使用。',
    'A full-page loading cover for first paint or route transitions.'),
  c('transition', 'basic', '过渡动画', 'Transition',
    '为元素的进入与离开提供淡入、缩放、滑动等预设动画。',
    'Fade, zoom and slide presets for element enter and leave.'),
  c('copy', 'basic', '复制', 'Copy',
    '一键将文本写入系统剪贴板，并给出统一的成功反馈。',
    'Writes text to the system clipboard with consistent success feedback.'),

  // --------------------------------------------------------------- layout
  c('layout', 'layout', '栅格布局', 'Layout',
    '24 等分的行列栅格，用于快速搭建等宽或按比例分栏的结构。',
    'A 24-column row/col grid for equal-width or proportional layouts.',
    ['row', 'col']),
  c('cell', 'layout', '单元格', 'Cell',
    '列表项的通用容器，可组合标题、描述、图标、右侧箭头与自定义内容。',
    'The general-purpose list row: title, label, icon, arrow and custom content.',
    ['cell', 'cell-group']),
  c('card', 'layout', '卡片', 'Card',
    '带头部、内容与底部三段结构的卡片容器。',
    'A card container with head, body and foot sections.'),
  c('grid', 'layout', '宫格', 'Grid',
    '等分的宫格布局，常用于首页金刚区与功能入口。',
    'An evenly divided grid, typically used for home-screen shortcuts.',
    ['grid', 'grid-item']),
  c('line', 'layout', '线条', 'Line',
    '可控制方向、长度、颜色与虚实的一根线。',
    'A single line with configurable direction, length, colour and dash style.'),
  c('divider', 'layout', '分割线', 'Divider',
    '区隔内容的分割线，支持居中或靠边的文字说明。',
    'A content separator that can carry centred or aligned text.'),
  c('gap', 'layout', '间隔槽', 'Gap',
    '用于制造区块之间的留白，可设置高度与背景色。',
    'Whitespace between blocks, with configurable height and background.'),
  c('box', 'layout', '盒子', 'Box',
    '带内边距、圆角与阴影的基础容器，替代手写 view 样式。',
    'A basic container with padding, radius and shadow, so you write less CSS.'),
  c('sticky', 'layout', '吸顶', 'Sticky',
    '滚动到指定位置时将内容固定在顶部。',
    'Pins content to the top once scrolling passes a threshold.'),
  c('swiper', 'layout', '轮播图', 'Swiper',
    '图片或自定义内容的轮播容器，内置多种指示器样式。',
    'A carousel for images or custom content, with several indicator styles.',
    ['swiper', 'swiper-indicator']),
  c('scroll-list', 'layout', '横向滚动', 'Scroll list',
    '横向滚动的列表容器，附带自定义滚动条指示。',
    'A horizontally scrolling list with its own scrollbar indicator.'),
  c('waterfall', 'layout', '瀑布流', 'Waterfall',
    '双列不等高瀑布流布局，自动把新内容放进较短的一列。',
    'A two-column masonry layout that always fills the shorter column next.'),
  c('safe-bottom', 'layout', '底部安全区', 'Safe bottom',
    '为 iPhone 等带 Home 指示条的机型撑出底部安全距离。',
    'Reserves the bottom safe-area inset on devices with a home indicator.'),
  c('status-bar', 'layout', '状态栏占位', 'Status bar',
    '撑出与系统状态栏等高的占位空间，配合自定义导航栏使用。',
    'A spacer as tall as the system status bar, for custom nav bars.'),

  // ----------------------------------------------------------------- form
  c('form', 'form', '表单', 'Form',
    '表单容器与校验器，配合 form-item 完成规则校验与错误提示。',
    'A form container and validator that pairs with form-item for rules and errors.',
    ['form', 'form-item']),
  c('input', 'form', '输入框', 'Input',
    '单行输入框，支持前后插槽、清除按钮、密码显隐与字数统计。',
    'A single-line input with prefix/suffix slots, clear button, password toggle and counter.'),
  c('textarea', 'form', '文本域', 'Textarea',
    '多行输入框，支持自动增高与字数限制。',
    'A multi-line input that grows with content and can enforce a length limit.'),
  c('checkbox', 'form', '复选框', 'Checkbox',
    '多选控件，支持组合校验、横竖排列与自定义图标。',
    'Multi-select control with group validation, layout options and custom icons.',
    ['checkbox', 'checkbox-group']),
  c('radio', 'form', '单选框', 'Radio',
    '单选控件，支持组合校验、横竖排列与自定义图标。',
    'Single-select control with group validation, layout options and custom icons.',
    ['radio', 'radio-group']),
  c('switch', 'form', '开关', 'Switch',
    '两种状态之间的切换控件，支持异步确认后再改变状态。',
    'Toggles between two states, optionally awaiting async confirmation first.'),
  c('slider', 'form', '滑动选择器', 'Slider',
    '通过拖动滑块在连续或离散区间内取值。',
    'Pick a value from a continuous or stepped range by dragging.'),
  c('rate', 'form', '评分', 'Rate',
    '星级评分控件，支持半星、只读与自定义图标。',
    'A star rating control with half stars, read-only mode and custom icons.'),
  c('search', 'form', '搜索', 'Search',
    '搜索输入框，内置搜索按钮、清除按钮与历史提示接口。',
    'A search field with built-in search and clear buttons.'),
  c('number-box', 'form', '步进器', 'Number box',
    '数字加减控件，支持步长、上下限与长按连加。',
    'A numeric stepper with step size, bounds and press-and-hold repetition.'),
  c('upload', 'form', '上传', 'Upload',
    '图片与文件上传，内置选择、预览、删除与进度展示。',
    'Image and file upload with selection, preview, removal and progress.'),
  c('picker', 'form', '选择器', 'Picker',
    '单列或多列的滚动选择器，支持联动数据。',
    'A single- or multi-column scroll picker, including cascading data.',
    ['picker', 'picker-column', 'picker-data']),
  c('datetime-picker', 'form', '时间选择器', 'Datetime picker',
    '日期与时间选择器，可自由组合年月日时分秒。',
    'A date and time picker; compose year, month, day, hour, minute and second freely.'),
  c('calendar', 'form', '日历', 'Calendar',
    '日历选择器，支持单日、多日与区间选择。',
    'A calendar picker supporting single, multiple and range selection.',
    ['calendar', 'calendar-strip']),
  c('keyboard', 'form', '键盘', 'Keyboard',
    '自定义键盘，提供数字、身份证与车牌号三种布局。',
    'Custom keyboards: numeric, ID-card and licence-plate layouts.',
    ['keyboard', 'car-keyboard', 'number-keyboard']),
  c('code', 'form', '验证码倒计时', 'Code',
    '无 UI 的倒计时逻辑组件，配合按钮实现"重新获取验证码"。',
    'A headless countdown that drives a "resend verification code" button.'),
  c('code-input', 'form', '验证码输入', 'Code input',
    '格子式验证码输入框，支持下划线、方框与横线三种样式。',
    'A boxed verification-code field, in box, underline or dash style.'),
  c('message-input', 'form', '验证码输入框', 'Message input',
    '与 code-input 类似的短信验证码输入，可自动聚焦与自动提交。',
    'An SMS-code field similar to code-input, with autofocus and auto-submit.'),
  c('select', 'form', '列选择器', 'Select',
    '从底部弹出的列表选择器，适合选项较少的场景。',
    'A bottom-sheet list picker, ideal when there are few options.'),
  c('cascader', 'form', '级联选择', 'Cascader',
    '多级联动选择器，常用于省市区、分类等树形数据。',
    'A cascading picker for tree data such as regions or categories.'),
  c('choose', 'form', '通用选择器', 'Choose',
    '数据驱动的通用选择器，一个组件覆盖单选、多选与搜索。',
    'A data-driven picker covering single select, multi select and search in one.'),
  c('color-picker', 'form', '颜色选择器', 'Color picker',
    '取色面板，支持色相、饱和度与透明度调节。',
    'A colour panel with hue, saturation and alpha controls.'),
  c('album', 'form', '相册', 'Album',
    '按九宫格排布的图片集合，点击可全屏预览。',
    'A grid of images with full-screen preview on tap.'),
  c('signature', 'form', '签名', 'Signature',
    '手写签名画板，可导出为图片。',
    'A handwriting signature pad that exports to an image.'),
  c('cropper', 'form', '图片裁剪', 'Cropper',
    '图片裁剪器，支持缩放、旋转与固定比例。',
    'An image cropper with zoom, rotation and fixed aspect ratios.'),
  c('city-locate', 'form', '城市选择', 'City locate',
    '城市列表选择器，带索引与定位当前城市能力。',
    'A city list picker with an index bar and current-location support.'),
  c('agreement', 'form', '协议勾选', 'Agreement',
    '用户协议勾选控件，内置未勾选时的抖动提示。',
    'A terms-of-service checkbox that shakes when unchecked.'),

  // ------------------------------------------------------------- feedback
  c('toast', 'feedback', '消息提示', 'Toast',
    '轻量的全局提示，支持成功、失败、加载等主题与完成回调。',
    'A lightweight global message with success, error and loading themes plus a completion callback.',
    ['toast', 'root-toast-host']),
  c('notify', 'feedback', '顶部通知', 'Notify',
    '从屏幕顶部滑入的通知条，适合非阻塞的结果反馈。',
    'A banner sliding in from the top for non-blocking feedback.'),
  c('modal', 'feedback', '模态框', 'Modal',
    '居中弹出的对话框，支持确认/取消、异步关闭与自定义内容。',
    'A centred dialog with confirm/cancel, async close and custom content.'),
  c('popup', 'feedback', '弹出层', 'Popup',
    '从上下左右或中间弹出的通用容器，是许多组件的底座。',
    'A generic container popping from any edge or the centre; the base of many components.'),
  c('overlay', 'feedback', '遮罩层', 'Overlay',
    '半透明遮罩，用于突出弹出内容并拦截背景交互。',
    'A translucent scrim that highlights a layer and blocks background interaction.'),
  c('action-sheet', 'feedback', '操作菜单', 'Action sheet',
    '从底部弹起的操作列表，支持标题、描述与危险操作样式。',
    'A bottom action list with title, description and destructive styling.',
    ['action-sheet', 'action-sheet-data']),
  c('alert', 'feedback', '警告提示', 'Alert',
    '常驻页面的提示条，用于说明需要关注但不打断流程的信息。',
    'An inline banner for information that matters but should not interrupt.'),
  c('notice-bar', 'feedback', '滚动通知', 'Notice bar',
    '横向滚动或纵向轮播的公告栏。',
    'An announcement bar that scrolls horizontally or rotates vertically.',
    ['notice-bar', 'row-notice', 'column-notice']),
  c('tooltip', 'feedback', '文字提示', 'Tooltip',
    '长按或点击后出现的气泡文字，可附带复制操作。',
    'A text bubble on tap or long press, optionally with a copy action.'),
  c('popover', 'feedback', '气泡卡片', 'Popover',
    '锚定在元素旁的气泡面板，可放入菜单或任意内容。',
    'A bubble panel anchored to an element, holding a menu or any content.'),
  c('swipe-action', 'feedback', '滑动操作', 'Swipe action',
    '左滑或右滑露出操作按钮，常用于列表项删除。',
    'Swipe a row to reveal action buttons, typically delete.',
    ['swipe-action', 'swipe-action-item']),
  c('collapse', 'feedback', '折叠面板', 'Collapse',
    '可展开收起的内容面板，支持手风琴模式。',
    'Expandable panels, with an optional accordion mode.',
    ['collapse', 'collapse-item']),
  c('guide', 'feedback', '引导蒙层', 'Guide',
    '高亮页面局部并配以说明的新手引导蒙层。',
    'An onboarding overlay that spotlights part of the screen and explains it.'),
  c('float-button', 'feedback', '悬浮按钮', 'Float button',
    '悬浮在页面之上的操作按钮，可展开为多个子操作。',
    'A floating action button that can fan out into several sub-actions.'),
  c('toolbar', 'feedback', '工具条', 'Toolbar',
    '弹出层顶部的取消/确认工具条，选择器类组件的公共部件。',
    'The cancel/confirm bar at the top of a popup; shared by picker components.'),
  c('goods-sku', 'feedback', '商品规格', 'Goods SKU',
    '电商商品规格选择弹层，处理规格组合与库存联动。',
    'An e-commerce SKU sheet handling attribute combinations and stock.'),

  // ----------------------------------------------------------- navigation
  c('navbar', 'nav', '自定义导航栏', 'Navbar',
    '替代系统导航栏，自动处理状态栏高度与返回逻辑。',
    'Replaces the system nav bar, handling status-bar height and back navigation.',
    ['navbar', 'navbar-mini']),
  c('tabbar', 'nav', '底部导航栏', 'Tabbar',
    '底部标签栏，支持徽标、凸起中间项与安全区适配。',
    'A bottom tab bar with badges, a raised centre item and safe-area handling.',
    ['tabbar', 'tabbar-item']),
  c('tabs', 'nav', '标签选项卡', 'Tabs',
    '横向标签页，支持滚动、徽标与自定义滑块。',
    'Horizontal tabs with scrolling, badges and a customisable indicator.',
    ['tabs', 'tabs-item', 'tabs-pro']),
  c('subsection', 'nav', '分段器', 'Subsection',
    '两到多个选项之间的分段切换控件。',
    'A segmented control for switching between a few options.'),
  c('steps', 'nav', '步骤条', 'Steps',
    '展示流程进度，支持横向、纵向与自定义节点。',
    'Shows progress through a flow, horizontally or vertically, with custom nodes.',
    ['steps', 'steps-item']),
  c('dropdown', 'nav', '下拉菜单', 'Dropdown',
    '从导航区域展开的筛选菜单，常用于列表页排序与过滤。',
    'A filter menu dropping from a nav area, for sorting and filtering lists.',
    ['dropdown', 'dropdown-item']),
  c('index-list', 'nav', '索引列表', 'Index list',
    '带右侧字母索引的长列表，滚动时自动吸顶分组标题。',
    'A long list with an alphabet index and sticky group headers.',
    ['index-list', 'index-anchor', 'index-item']),
  c('back-top', 'nav', '返回顶部', 'Back to top',
    '滚动一段距离后出现的回到顶部按钮。',
    'A back-to-top button that appears after scrolling far enough.'),
  c('pagination', 'nav', '分页器', 'Pagination',
    '分页导航控件，支持上下页与页码跳转。',
    'Page navigation with prev/next and direct page jumps.'),
  c('empty', 'nav', '内容为空', 'Empty',
    '空状态占位图，内置多种语义化插画。',
    'An empty-state placeholder with several built-in illustrations.'),
  c('no-network', 'nav', '无网络提示', 'No network',
    '断网时的全屏提示，提供重试与跳转系统设置入口。',
    'A full-screen offline notice with retry and system-settings shortcuts.'),
  c('cate-tab', 'nav', '分类选项卡', 'Category tab',
    '左侧分类、右侧内容的二级联动导航。',
    'Two-level navigation with categories on the left and content on the right.'),
  c('section', 'nav', '章节标题', 'Section',
    '带右侧"更多"入口的区块标题。',
    'A block heading with an optional "more" affordance on the right.'),
  c('tree', 'nav', '树形控件', 'Tree',
    '可展开收起的层级数据展示，支持复选与懒加载。',
    'Hierarchical data with expand/collapse, checkboxes and lazy loading.'),

  // ----------------------------------------------------------------- data
  c('list', 'data', '长列表', 'List',
    '为长列表做了回收优化的容器，配合 list-item 使用。',
    'A recycling container for long lists, used with list-item.',
    ['list', 'list-item']),
  c('virtual-list', 'data', '虚拟列表', 'Virtual list',
    '只渲染可视区域的虚拟滚动列表，可承载上万条数据。',
    'Renders only the visible window, so it scales to tens of thousands of rows.',
    ['virtual-list', 'refresh-virtual-list']),
  c('table', 'data', '表格', 'Table',
    '数据表格，支持固定表头、自定义列与单元格插槽。',
    'A data table with a fixed header, custom columns and cell slots.',
    ['table', 'table2', 'td', 'th', 'tr']),
  c('skeleton', 'data', '骨架屏', 'Skeleton',
    '加载中的占位骨架，支持段落、头像与图片形状。',
    'Loading placeholders in paragraph, avatar and image shapes.'),
  c('line-progress', 'data', '线形进度条', 'Line progress',
    '横向进度条，可在条内显示百分比。',
    'A horizontal progress bar that can show its percentage inline.'),
  c('circle-progress', 'data', '圆形进度条', 'Circle progress',
    '环形进度指示器，适合展示完成度与得分。',
    'A ring progress indicator for completion rates and scores.'),
  c('count-down', 'data', '倒计时', 'Count down',
    '毫秒级倒计时，支持自定义时间格式与插槽渲染。',
    'A millisecond countdown with custom formats and slot rendering.'),
  c('count-to', 'data', '数字滚动', 'Count to',
    '数字从起始值滚动到目标值的动画。',
    'Animates a number from a start value to a target value.'),
  c('loadmore', 'data', '加载更多', 'Load more',
    '列表底部的加载状态提示，包含加载中、加载完成与没有更多三态。',
    'A list footer with loading, loaded and no-more states.'),
  c('read-more', 'data', '展开阅读更多', 'Read more',
    '超出指定高度时折叠内容并给出展开按钮。',
    'Collapses content past a height threshold and offers an expand button.'),
  c('lazy-load', 'data', '图片懒加载', 'Lazy load',
    '进入视口后才真正加载图片，减少首屏请求。',
    'Defers image loading until it enters the viewport.'),
  c('pull-refresh', 'data', '下拉刷新', 'Pull refresh',
    '下拉触发刷新的容器，支持自定义下拉区域内容。',
    'A pull-to-refresh container with a customisable pull area.'),
  c('dragsort', 'data', '拖拽排序', 'Drag sort',
    '长按拖动重新排序的列表或宫格。',
    'A list or grid reordered by long-press and drag.'),
  c('coupon', 'data', '优惠券', 'Coupon',
    '优惠券卡片样式，含票根缺口与可用/失效状态。',
    'A coupon card with ticket notches and available/expired states.'),

  // ---------------------------------------------------------------- other
  c('parse', 'other', '富文本解析', 'Rich text',
    '把 HTML 字符串解析为各端原生节点渲染。',
    'Parses an HTML string into native nodes on every platform.'),
  c('markdown', 'other', 'Markdown 渲染', 'Markdown',
    '渲染 Markdown 文本，支持代码块与表格。',
    'Renders Markdown text, including code blocks and tables.'),
  c('qrcode', 'other', '二维码', 'QR code',
    '在本地生成二维码，无需服务端参与。',
    'Generates a QR code locally, with no server round trip.'),
  c('barcode', 'other', '条形码', 'Barcode',
    '在本地生成一维条形码。',
    'Generates a one-dimensional barcode locally.'),
  c('poster', 'other', '海报生成', 'Poster',
    '将图文合成为一张可保存分享的海报图片。',
    'Composites text and images into a shareable poster.'),
  c('canvas', 'other', '画布', 'Canvas',
    '统一各端差异的画布封装，是二维码、海报等组件的底层。',
    'A canvas wrapper that hides platform differences; the base for QR codes and posters.'),
  c('pdf-reader', 'other', 'PDF 阅读器', 'PDF reader',
    '内嵌 PDF 浏览器，支持翻页与缩放。',
    'An embedded PDF viewer with paging and zoom.'),
  c('short-video', 'other', '短视频', 'Short video',
    '全屏上下滑动的短视频播放容器。',
    'A full-screen, vertically swipeable short-video player.'),
  c('novel-reader', 'other', '小说阅读器', 'Novel reader',
    '带目录、翻页与阅读设置的长文阅读器。',
    'A long-form reader with catalogue, paging and reading settings.'),
  c('view', 'other', '视图容器', 'View',
    '最底层的视图容器，统一各端的盒模型与样式写法。',
    'The lowest-level view container, unifying the box model across platforms.'),
]

/** id -> meta */
export const metaMap = Object.fromEntries(meta.map((m) => [m.id, m]))

/** Every upstream folder covered by the curated pages. */
export const coveredDetectIds = new Set(meta.flatMap((m) => m.detect))
